---
title: "Homework 5"
output: github_document
---

```{r setup}
library(tidyverse)


knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6,
  out.width = "90%")
```

# Problem 1
```{r}
# Load dataset
homicide = 
  read_csv("./data/homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state), 
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved", 
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

```{r}
# the total number of homicides
homicide %>% 
  count(city_state)

# the number of unsolved homicides
homicide %>%  
  filter(resolution == "unsolved") %>% 
  count(city_state)
```

Focus on Baltimore, MD

```{r}
baltimore_df = 
  homicide %>% 
  filter(city_state == "BaltimoreMD")

# estimate the proportion of homicides that are unsolved
baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"), 
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved), 
  n = baltimore_summary %>%  pull(n)
)

baltimore_test %>% 
  broom::tidy()
```

Iterate across cities

```{r}
# write a function
prop_test_function = function(city_df){
  city_summary = 
  city_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"), 
    n = n()
  )

city_test = 
  prop.test(
  x = city_summary %>% pull(unsolved), 
  n = city_summary %>%  pull(n)
)
  return(city_test)
}

```

```{r}
# iterate the pro_test_function across cities by nesting dataframes together
results_df = 
  homicide %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function), 
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
    geom_point() +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(
      title = "Estimates and CIs for each City", 
      x = "City and State", 
      y = "Estimate"
    )
```

